### ISSUE TITLE
Bring back: flarum-lang/dutch

### ISSUE THREAD

**Issue by Equinemarkt** [Free-Flarum/freeflarum.com#375]
## Packagist URL for extension:

https://packagist.org/packages/flarum-lang/dutch

## Why should this extension be installed?

Not many Dutch people will use Flarum I guess, but my (growning) forum is 100% Dutch. Also I started (and still am) to fill in this extension myself, because I need it for my own Forum. I have FOF Linguist but I personally can't handle to rewrite everything again from English to Dutch. So please can this feature be placed back into FreeFlarum? Even if you're not Dutch you can still vote Yes?
I'm someone that will remove her forum when it's starting to outgrow FreeFlarum, to give the smaller a change and to not overwork the server etc. 

Thanks for reading this post. Please upvote. 

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by CWKevo** [comment]
Well, language packs aren't usually that resource intensive, and I see why would you need it - re-installed!
